#!/usr/bin/env bash
#Displays numbers from 1 to 100
k=1

while [ $k -le "100" ] ; do
    if ((k % 3 == 0 && k % 5 == 0)) ; then
        echo "FizzBuzz"
    elif ((k % 3 == 0)) ; then 
        echo "Fizz"
    elif ((k % 5 == 0)) ; then 
        echo "Buzz"
    else
        echo $k
    fi

    ((k += 1))
done