#!/usr/bin/env bash
# This is a script that displays "Best School" 10 times,
# but for the 9th iteration, displays Holberton School
# and then Hi on a new line.
k=1

while [ $k -lt "10" ]
do
    echo "Best School"

    if [ $k -eq "9" ]
    then
        echo "Hi"
        echo "Best School"
    fi

    ((k += 1))
done