#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
#
#   - Displays 4 and then bad luck from China for the 4th loop iteration
#   - Displays 9 and then bad luck from Japan for the 9th loop iteration
#   - Displays 17 and then bad luck from Italy for the 17th loop iteration
k=1

while [ $k -le "20" ]
do
    case $k in
        4)
            echo $k
            echo "bad luck from China"
            ;;
        9)
            echo $k
            echo "bad luck from Japan"
            ;;
        17)
            echo $k
            echo "bad luck from Italy"
            ;;
        *)
            echo $k
            ;;
    esac

    (("k += 1"))
done